import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalQuoteSection from "./components/ConditionalQuoteSection";
import Footer from "./components/Footer";
import TopHeader from "./components/TopHeader";
import Navbar from "./components/Navbar";
import FloatingCallButton from "./components/FloatingCallButton";
import WhatsAppButton from "./components/WhatsAppButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopHeader />
        <Navbar />
        {children}
        <ConditionalQuoteSection />
        <Footer />
        <FloatingCallButton />
        <WhatsAppButton />
      </body>
    </html>
  );
}
